version: '3'

services:
  nodejs-service:
    build: ./docker-node
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8000:8000
      - 9229:9229
    command: npm start
  react-service:
    build: ./docker-react
    volumes:
      - .:/app
    ports:
      - 3000:3000
      - 35729:35729
    command: npm start